/**
 * @file NetPynucastro.h
 * @brief Unified generic wrapper for ANY network generated by pynucastro.
 * By including "network_properties.H", this adapts to aprox19, aprox21, iso7, etc.
 * dynamically at compile time based on the CMake include path.
 */
#pragma once

#include <string>
#include <vector>
#include <algorithm>
#include <cctype>
#include "../../data/GlobalDefs.h"
#include "../../core/RuntimeParams.h"
#include "../../physics/species/Species.h"
#include "../../numerics/linalg/DenseWrap.h"
#include "../../numerics/linalg/SparseWrap.h"

// pynucastro constants (e.g. NumSpecTotal, aion, zion, spec_names)
#include "network_properties.H"

struct NetPynucastro
{
    // =======================================================
    // 1. Compile-time Constants
    // =======================================================
    static constexpr int NUM_SPECIES = NumSpecTotal;
    static constexpr int ODE_NEQ = NumSpecTotal + 1; // +1 for Temperature

    // =======================================================
    // 2. Info Interface
    // =======================================================
    static std::string get_network_name() { return "PynucastroNetwork"; }

    // =======================================================
    // 3. Setup Helpers (Eliminates Boilerplate in Case.cpp)
    // =======================================================
    
    /**
     * @brief Automatically register all isotopes from the linked pynucastro network.
     */
    static void RegisterSpecies(SpeciesManager& specs)
    {
        for (int i = 0; i < NumSpecTotal; ++i)
        {
            // Name, Mass (A), Atomic Number (Z), Gamma (Monatomic default), Cv
            specs.add_species(spec_names[i], aion[i], zion[i], 1.6667, 0.0);
        }
    }

    /**
     * @brief Reads initial mass fractions from SimConfig (.par file) and normalizes them.
     * Looks for parameters like "X_c12 = 0.5".
     */
    static void SetupInitialFractions(SimConfig& config, const SpeciesManager& specs, std::vector<double>& X_out)
    {
        X_out.assign(specs.count(), 1e-20); // Prevent exact zeroes in network
        double sum_X = 0.0;
        for (int i = 0; i < specs.count(); ++i)
        {
            std::string name = specs.get_name(i);
            
            // Construct target lowercase key, e.g. "xhe4"
            std::string target = "x" + name;
            std::transform(target.begin(), target.end(), target.begin(), ::tolower);

            double val = 0.0;
            // Iterate over all custom parameters to find a case-insensitive match
            for (const auto& kv : config.custom_params) {
                std::string k_lower = kv.first;
                std::transform(k_lower.begin(), k_lower.end(), k_lower.begin(), ::tolower);
                if (k_lower == target) {
                    val = kv.second;
                    break;
                }
            }

            X_out[i] += val;
            sum_X += X_out[i];
        }

        // Normalize if non-zero
        if (sum_X > 0.0)
        {
            for (int i = 0; i < specs.count(); ++i)
            {
                X_out[i] /= sum_X;
            }
        }
    }

    // =======================================================
    // 4. Physical Evaluation Interfaces (Implemented in .cpp)
    // =======================================================
    static void eval_rhs(const double *Y, double rho, double *RHS, double &enuc);
    static void eval_jacobian(const double *Y, double rho, DenseMatrixData &J_dense);
    static void eval_jacobian(const double *Y, double rho, SparseMatrixData &J_sparse);
};
