import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {validateCorePreview} from '../src/host/previewValidation.ts';
import {loadPar,editPar,revertPar} from '../src/state/parState.ts';
import {serializePar} from '../src/data/ParDocument.ts';
import {EditHistory} from '../src/state/editHistory.ts';
function example(name:string){return JSON.parse(readFileSync(new URL('../../src/api/examples/core-a/'+name+'.json',import.meta.url),'utf8'));}
test('real Core A fixtures retain explicit, default, fallback and failure metadata',()=>{for(const name of ['explicit','default','fallback','outside','nonfinite']){const v=example(name);const result=validateCorePreview(v,v.identity);assert.equal(result.parameterMetadata?.parameters[0]?.key,name==='nonfinite'?undefined:'x_pos');assert.equal(result.graphicalBindings?.items.length,name==='nonfinite'?undefined:name==='outside'?0:1);}});
test('untrusted metadata / binding disagreement is rejected; unknown versions ignored',()=>{for(const change of [(v:ReturnType<typeof example>)=>v.parameterMetadata.parameters[0].effectiveValue=Infinity,(v:ReturnType<typeof example>)=>v.graphicalBindings.items[0].coordinate=.9,(v:ReturnType<typeof example>)=>v.graphicalBindings.items[0].axis='x2',(v:ReturnType<typeof example>)=>v.parameterMetadata.parameters.push(v.parameterMetadata.parameters[0])]){const v=example('explicit');change(v);assert.throws(()=>validateCorePreview(v,v.identity));}const v=example('explicit');v.parameterMetadata.version='future';v.graphicalBindings.version='future';assert.equal(validateCorePreview(v,v.identity).parameterMetadata,undefined);});
test('missing parameter insertion preserves original bytes and a single Undo removes assignment',()=>{for(const raw of ['a=1\n# tail\n','a=1\r\n# tail','\ufeffa=1\r\n','# x_pos = 9\na=1']){const before=loadPar('x.par',raw);const next=editPar(before,'x_pos','0.35');const out=serializePar(next.document,next.changes);assert.ok(out.startsWith(raw));assert.equal((out.match(/^x_pos = /gm)||[]).length,1);const history=new EditHistory<typeof before>();history.record(before,next);assert.equal(serializePar(history.undo(next).document),raw);assert.equal(serializePar(revertPar(next).document),raw);assert.throws(()=>serializePar(before.document,{'bad\nkey':'1'}));}});
