import test from 'node:test';import assert from 'node:assert/strict';
import {readFile,writeFile,readdir,rm,chmod} from 'node:fs/promises';
import {previewFixture,previewFinished} from './preview-fixture.ts';
import {PreviewRunner} from '../host/previewRunner.ts';
import {BuildRunner} from '../host/buildRunner.ts';
import {createHostServer,listenLocal} from '../host/server.ts';
import {PROTOCOL_VERSION} from '../src/host/contracts.ts';
test('fixed Preview runs unsaved stdin, preserves files and provenance, and retains success on failure',async()=>{const f=await previewFixture();try{await writeFile(f.root+'/disk.par','original');const before=await readdir(f.root);const a=await f.preview.start(f.request);const s=await previewFinished(f.preview);assert.equal(s.state,'succeeded');assert.equal(s.result?.identity.requestId,a.requestId);assert.equal(s.result?.identity.configRevision,f.request.configRevision);assert.equal(s.result?.identity.buildId,'build-id');assert.equal(await readFile(f.root+'/disk.par','utf8'),'original');assert.deepEqual(await readdir(f.root),before);await writeFile(f.root+'/case.cpp','changed');assert.equal((await f.preview.readiness()).ready,false);await assert.rejects(f.preview.start(f.request),/Build required/);assert.equal(f.preview.snapshot().result?.identity.requestId,a.requestId);}finally{await f.cleanup();}});
test('missing manifest, modified executable and profile mismatch disable Preview',async()=>{const f=await previewFixture();try{await writeFile(f.root+'/build/bin/ARCH','changed');assert.equal((await f.preview.readiness()).ready,false);await rm(f.root+'/studio/.local',{recursive:true});const b=new BuildRunner(f.root,'p',f.p);await b.initialize();const r=new PreviewRunner(b,f.preview.profile);assert.equal((await r.readiness()).ready,false);const mismatch=new PreviewRunner(f.build,{...f.preview.profile,buildProfileId:'other'});assert.equal((await mismatch.readiness()).ready,false);}finally{await f.cleanup();}});
test('strict request rejects command injection, wrong identity, unknown profile and bounds',async()=>{const f=await previewFixture();try{for(const extra of [{program:'/bin/sh'},{args:['x']},{cwd:'/tmp'},{env:{}},{shell:true},{profileId:'unknown'},{projectId:'other'},{configRevision:'wrong'},{requestedSampleCount:4097},{caseId:'Other'},{configText:'x'.repeat(1048577)}])await assert.rejects(f.preview.start({...f.request,...extra}));assert.equal(f.preview.isActive(),false);}finally{await f.cleanup();}});
test('cancellation owns the current process, rejects arbitrary ID and blocks simultaneous Build',async()=>{const f=await previewFixture('hang',2000);try{const a=await f.preview.start(f.request);await assert.rejects(f.preview.start(f.request),/already generating/);await assert.rejects(f.build.start('p',f.p.id),/Preview is active/);assert.throws(()=>f.preview.cancel('other'));await new Promise(r=>setTimeout(r,100));f.preview.cancel(a.requestId);assert.equal((await previewFinished(f.preview)).state,'cancelled');assert.equal(f.preview.snapshot().result,undefined);}finally{await f.cleanup();}});
for(const mode of ['hang','bad','wrong','huge','exit'])test('Preview rejects '+mode,async()=>{const f=await previewFixture(mode,200);try{await f.preview.start(f.request);const s=await previewFinished(f.preview);assert.equal(s.state,'failed');assert.equal(s.result,undefined);assert.ok(s.error);}finally{await f.cleanup();}});
test('source changed during Preview discards successful process output',async()=>{const f=await previewFixture('slow');try{await f.preview.start(f.request);await writeFile(f.root+'/case.cpp','new source');const s=await previewFinished(f.preview);assert.equal(s.state,'failed');assert.match(s.error!,/Build changed/);assert.equal(s.result,undefined);}finally{await f.cleanup();}});
test('HTTP Preview enforces origin, protocol, no arbitrary fields, and bounded body',async()=>{const f=await previewFixture();const reader={preview:f.preview,snapshot:()=>({session:{projectId:'p'},host:{}}) as never,refresh:async()=>({}) as never};const server=createHostServer(reader,'http://127.0.0.1:4179');try{await listenLocal(server,0);const port=(server.address() as {port:number}).port;const url=`http://127.0.0.1:${port}/api/preview`;const headers={'Origin':'http://127.0.0.1:4179','X-ARCH-Studio':'1','X-ARCH-Protocol':PROTOCOL_VERSION,'Content-Type':'application/json'};assert.equal((await fetch(url,{method:'POST',headers:{...headers,Origin:'http://evil'},body:'{}'})).status,403);assert.equal((await fetch(url,{method:'POST',headers:{...headers,'X-ARCH-Protocol':'1.2'},body:'{}'})).status,426);assert.equal((await fetch(url,{method:'POST',headers,body:JSON.stringify({...f.request,program:'sh'})})).status,400);assert.equal((await fetch(url,{method:'POST',headers,body:JSON.stringify({...f.request,configText:'x'.repeat(1048577)})})).status,413);}finally{await new Promise<void>(r=>server.close(()=>r()));await f.cleanup();}});

test('non-executable binary reports spawn failure without leaving an active request',async()=>{const f=await previewFixture();try{await chmod(f.root+'/build/bin/ARCH',0o644);await f.preview.start(f.request);const s=await previewFinished(f.preview);assert.equal(s.state,'failed');assert.match(s.error!,/could not start/);}finally{await f.cleanup();}});
