import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {catalog,catalogCoordinates,parameterUnit} from '../src/data/parameterCatalog.ts';
import {parameterPlacement,runtimeOrder,runtimeSection,forbiddenParameters} from '../src/data/parameterLayout.ts';
import {validateConfigurationSchema,validateConfigurationInspection} from '../src/host/configurationValidation.ts';
import {loadPar,editPar,removeForbiddenParameter} from '../src/state/parState.ts';
import {serializePar} from '../src/data/ParDocument.ts';
import {EditHistory} from '../src/state/editHistory.ts';
const schema=validateConfigurationSchema(JSON.parse(await readFile(new URL('./fixtures/mainline-config-schema.json',import.meta.url),'utf8')));
const rawInspection=JSON.parse(await readFile(new URL('../../src/api/examples/configuration/inspect-sod.json',import.meta.url),'utf8'));
test('Runtime ordering is presentation only; unknown schema additions remain reachable',()=>{
 const rows=catalog(schema.parameters,{});
 const sorted=rows.filter(r=>r.parameter.group==='Runtime').sort(runtimeOrder).map(r=>r.parameter.key);
 assert.deepEqual(sorted.slice(0,7),['compute_backend','time_integrator','solver','hll_wave_speed','reconstruct','limiter','cfl']);
 assert.equal(runtimeSection('dt_max'),'Advanced repair / device / time');
 assert.equal(runtimeSection('restart_file'),'Checkpoint / Restart');
 const future={...schema.parameters[0],key:'future_key',group:'Future group'};
 assert.ok(catalog([...schema.parameters,future],{}).some(r=>r.parameter.key==='future_key'));
 assert.ok(rows.find(r=>r.parameter.key==='eos_table_path'));
 assert.ok(rows.find(r=>r.parameter.key==='eos_helm_table_path'));
});
test('conditional controls retain errors and use current Core coefficient authority',()=>{
 const values={gravity_type:'none',use_diffusion:'false',nblockx1:'1',nblockx2:'0',nblockx3:'0'};
 const rows=catalog(schema.parameters,values),coordinates=catalogCoordinates(schema,values);
 const row=(key:string)=>rows.find(r=>r.parameter.key===key)!;
 assert.equal(parameterPlacement(row('gravity_G'),rows,undefined,coordinates,{}),'inactive');
 assert.equal(parameterPlacement(row('gravity_G'),rows,undefined,coordinates,{gravity_G:'invalid'}),'common');
 const external=catalog(schema.parameters,{...values,gravity_type:'external'});
 assert.equal(parameterPlacement(row('gravity_g_x'),external,undefined,coordinates,{}),'common');
 assert.equal(parameterPlacement(row('gravity_g_y'),external,undefined,coordinates,{}),'inactive');
 assert.equal(parameterPlacement(row('gravity_G'),external,undefined,coordinates,{}),'inactive');
 const self=catalog(schema.parameters,{...values,gravity_type:'self'});
 assert.equal(parameterPlacement(row('gravity_rtol'),self,undefined,coordinates,{}),'advanced');
 assert.equal(parameterPlacement(row('gravity_g_x'),self,undefined,coordinates,{}),'inactive');
 const enabled=catalog(schema.parameters,{...values,use_diffusion:'true',use_thermal_diff:'true'});
 assert.equal(parameterPlacement(row('alpha_therm'),enabled,undefined,coordinates,{}),'inactive');
 const inspected=structuredClone(rawInspection);
 inspected.diffusion={version:'1',enabled:true,modeEditable:false,source:'constant',sourceScope:'configuration',forbiddenExplicitKeys:[],channels:[{coefficientKey:'alpha_therm',toggleKey:'use_thermal_diff',constantInputAllowed:true,unit:'cm^2/s'}]};
 const valid=validateConfigurationInspection(inspected,inspected.identity);
 assert.equal(parameterPlacement(row('alpha_therm'),enabled,valid,coordinates,{}),'common');
 inspected.diffusion.channels[0].constantInputAllowed=false;
 assert.equal(parameterPlacement(row('alpha_therm'),enabled,inspected,coordinates,{}),'inactive');
 inspected.diffusion.modeEditable=true;
 assert.throws(()=>validateConfigurationInspection(inspected,inspected.identity),/diffusion/);
 const bad=structuredClone(schema);bad.parameters.find(p=>p.presentation?.toggle)!.presentation!.toggle!.offValue=NaN;
 assert.throws(()=>validateConfigurationSchema(bad),/toggle/);
 assert.equal(parameterUnit({...schema.parameters[0],units:{status:'not-applicable',unit:null}}),'');
});
test('Core forbidden removal is explicit, byte preserving, one Undo and reversible by later editing',()=>{
 const inspection=structuredClone(rawInspection);
 inspection.diagnostics=[{severity:'error',code:'INAPPLICABLE_PARAMETER',parameterKey:'alpha_therm',message:'Explicit coefficient forbidden'}];
 const allowed=forbiddenParameters(inspection);
 const raw='# note\r\nalpha_therm = 1 # first\r\ncustom = keep\r\nalpha_therm = 2 # effective\r\n';
 const state=loadPar('case.par',raw),history=new EditHistory<typeof state>();
 assert.equal(serializePar(state.document,state.changes,state.removedKeys),raw);
 assert.throws(()=>removeForbiddenParameter(state,'custom',allowed),/Core diagnostic/);
 const next=removeForbiddenParameter(state,'alpha_therm',allowed);history.record(state,next);
 assert.equal(serializePar(next.document,next.changes,next.removedKeys),'# note\r\n# first\r\ncustom = keep\r\n# effective\r\n');
 const restored=history.undo(next);assert.equal(serializePar(restored.document,restored.changes,restored.removedKeys),raw);
 const edited=editPar(next,'alpha_therm','3');
 assert.match(serializePar(edited.document,edited.changes,edited.removedKeys),/alpha_therm = 3 # effective/);
});
