import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {validateConfigurationSchema} from '../src/host/configurationValidation.ts';
import {isRetiredParameter,loadPar,editPar,removeRetiredParameter,exportPar,exportDraft,parErrors,revertPar,parStatus} from '../src/state/parState.ts';
import {serializePar} from '../src/data/ParDocument.ts';
import {EditHistory} from '../src/state/editHistory.ts';
const schema=validateConfigurationSchema(JSON.parse(await readFile(new URL('../../src/api/examples/configuration-v3/schema.json',import.meta.url),'utf8')));
const retiredKeys=schema.retiredKeys;
for(const key of retiredKeys)test('explicit migration preserves raw / comments / duplicates / Undo / reopen: '+key,()=>{
 const raw='# before\r\n'+key+' = false # retained note\r\nunknown = keep\r\n'+key+' = true\r\nnblockx2=0\r\nnblockx3=0';
 const original=loadPar('legacy.par',raw);
 assert.equal(serializePar(original.document,original.changes),raw);
 assert.ok(parErrors(original,schema.parameters,retiredKeys)[key]);assert.throws(()=>exportPar(original,schema.parameters,retiredKeys));
 assert.throws(()=>editPar(original,key,'false',retiredKeys),/Retired/);
 const edited=editPar(original,'unknown','changed',retiredKeys);
 const next=removeRetiredParameter(edited,key,retiredKeys);
 const history=new EditHistory<typeof original>();history.record(edited,next);
 assert.equal(next.document.raw,raw);
 const text=exportPar(next,schema.parameters,retiredKeys).text;
 assert.ok(text.includes('# retained note\r\n'));assert.ok(text.includes('unknown = changed\r\n'));
 assert.ok(!text.includes(key+' ='));assert.equal(parStatus(next,schema.parameters,retiredKeys),'dirty');
 const undone=history.undo(next);assert.deepEqual(undone,edited);
 assert.equal(serializePar(undone.document,undone.changes,undone.removedKeys),serializePar(edited.document,edited.changes));
 assert.equal(exportPar(history.redo(undone),schema.parameters,retiredKeys).text,text);
 assert.equal(serializePar(revertPar(next).document),raw);
 assert.equal(exportPar(loadPar('saved.par',text),schema.parameters,retiredKeys).text,text);
});
test('normal key cannot use retired removal; retired names cannot be inserted as Custom',()=>{
 const state=loadPar('a.par','nblockx2=0\nnblockx3=0\n');
 assert.throws(()=>removeRetiredParameter(state,'x_pos',retiredKeys));
 for(const key of retiredKeys)assert.throws(()=>editPar(state,key,'1',retiredKeys));
});

test('Core metadata alone reserves a newly retired key; pending classification preserves the draft',()=>{
 const key=['future',schema.parameters[0].key,'retired'].join('_');
 const future=validateConfigurationSchema({...structuredClone(schema),retiredKeys:[key]});
 const raw='# before\r\n'+key+' = 1 # first\r\nunknown = keep\r\n'+key+' = 2 # second\r\n';
 const original=loadPar('future.par',raw);
 assert.equal(exportDraft(original).text,raw);
 assert.equal(isRetiredParameter(key,future.retiredKeys),true);
 assert.equal(isRetiredParameter(schema.retiredKeys[0],future.retiredKeys),false);
 assert.match(parErrors(original,future.parameters,future.retiredKeys)[key],/RETIRED_PARAMETER/);
 assert.throws(()=>editPar(original,key,'3',future.retiredKeys),/Retired/);
 assert.throws(()=>exportPar(original,future.parameters,future.retiredKeys),/invalid/);
 // Without matching Core metadata the token is unclassified, never guessed retired.
 assert.equal(isRetiredParameter(key,undefined),false);
 assert.equal(parErrors(original,undefined,undefined)[key],undefined);
 assert.throws(()=>removeRetiredParameter(original,key,undefined),/Only retired/);
 assert.equal(exportDraft(original).text,raw);
 const edited=editPar(original,'unknown','changed',future.retiredKeys);
 const removed=removeRetiredParameter(edited,key,future.retiredKeys);
 const history=new EditHistory<typeof original>();history.record(edited,removed);
 assert.equal(removed.document.raw,raw);
 assert.equal(exportPar(removed,future.parameters,future.retiredKeys).text,'# before\r\n# first\r\nunknown = changed\r\n# second\r\n');
 assert.equal(parErrors(removed,future.parameters,future.retiredKeys)[key],undefined);
 assert.throws(()=>editPar(removed,key,'3',future.retiredKeys),/Retired/);
 const undone=history.undo(removed);assert.deepEqual(undone,edited);
 assert.equal(exportDraft(undone).text,exportDraft(edited).text);
 assert.match(parErrors(undone,future.parameters,future.retiredKeys)[key],/RETIRED_PARAMETER/);
});
