"""Generate isolated Jeans numeric references; no EOS/AMR scientific acceptance."""
from decimal import Decimal, localcontext
import json
import math
import argparse

PI = "3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117067982148086513282306647093844609550582231725359"
CASES = [(1.0, 1.0, 1.0), (4.0, 1.0, 1.0), (1.0, 4.0, 1.0), (1.0, 1.0, 4.0), (1e-320, 1e-300, 1e+20), (1e+300, 1e+300, 1.0), (1e-300, 1e+300, 1e+300), (1e+300, 1e-300, 1e-300)]
def exponent_cases():
    """Finite binary64 inputs spanning low density and cancelling exponents."""
    exponents = [-1074, -1022, -600, -1, 0, 600, 1023]
    cases = list(CASES)
    for rho_exp in exponents:
        for sound_exp in exponents:
            for spacing_exp in [-1074, -1022, -600, 0, 600, 1023]:
                cases.append((math.ldexp(1.0, rho_exp),
                              math.ldexp(1.0, sound_exp),
                              math.ldexp(1.0, spacing_exp)))
    return list(dict.fromkeys(cases))

def references(precision, cases=CASES):
    with localcontext() as context:
        context.prec = precision
        return [
            float((Decimal(PI) * Decimal.from_float(cs2) /
                   (Decimal("6.67430e-8") * Decimal.from_float(rho))).sqrt() /
                  Decimal.from_float(h)).hex()
            for rho, cs2, h in cases
        ]
def cpp_fixture(cases):
    low, high = references(80, cases), references(120, cases)
    if low != high:
        raise RuntimeError("Reference precision did not converge to the same double")
    rows = []
    counts = {"valid": 0, "zero": 0, "infinite": 0}
    for (rho, cs2, h), expected in zip(cases, high):
        value = float.fromhex(expected)
        state = "infinite" if math.isinf(value) else "zero" if value == 0 else "valid"
        counts[state] += 1
        literal = "std::numeric_limits<double>::infinity()" if state == "infinite" else expected
        rows.append("    {%s, %s, %s, %s}," % (rho.hex(), cs2.hex(), h.hex(), literal))
    text = """// Generated by validation/gravity/jeans_numeric_reference.py --cpp.
// Independent Decimal 80/120-digit references; not an EOS/AMR science budget.
#pragma once
#include <array>
#include <limits>
namespace JeansNumericReference {
struct Case { double rho, cs2, h, expected; };
inline constexpr std::array<Case, %d> cases{{
%s
}};
} // namespace JeansNumericReference
""" % (len(rows), "\n".join(rows))
    return text, counts

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--cpp", action="store_true", help="emit deterministic exponent-grid C++ fixture")
    args = parser.parse_args()
    if args.cpp:
        print(cpp_fixture(exponent_cases())[0], end="")
    else:
        low, high = references(80), references(120)
        if low != high:
            raise RuntimeError("Reference precision did not converge to the same double")
        print(json.dumps([
            dict(density=rho.hex(), soundSpeedSquared=cs2.hex(), maxActiveSpacing=h.hex(),
                 expectedCells=expected)
            for (rho, cs2, h), expected in zip(CASES, high)
        ], indent=2))
