import {useEffect,useRef,useState} from 'react';
import {useHost} from './hostContext';
import {buildRequest,validateBuildSnapshot,validateBuildEvents} from './BuildAdapter';
import type {BuildSnapshot,BuildEvents} from './contracts';
export function BuildPanel({onActive}:{onActive:(active:boolean)=>void}){
 const {snapshot,connected}=useHost();const projectId=snapshot?.session.projectId;
 const [status,setStatus]=useState<BuildSnapshot>();const [log,setLog]=useState<BuildEvents>();const [error,setError]=useState('');const [pending,setPending]=useState(false);const [clear,setClear]=useState({buildId:'',sequence:0});const generation=useRef(0);
 useEffect(()=>{const gen=++generation.current;let timer:ReturnType<typeof setTimeout>;let gone=false;
  async function poll(){if(!projectId||!connected)return;try{const next=validateBuildSnapshot(await buildRequest('/api/build/status'),projectId);if(gone||gen!==generation.current)return;setStatus(next);onActive(!!next.activeBuildId);const id=next.activeBuildId??next.latestResult?.buildId;if(id){const events=validateBuildEvents(await buildRequest('/api/build/'+id+'/events'),projectId,id);if(!gone&&gen===generation.current)setLog(events);}setError('');}catch(e){if(!gone)setError(e instanceof Error?e.message:'Build unavailable');}finally{if(!gone)timer=setTimeout(()=>void poll(),1000);}}
  void poll();return()=>{gone=true;clearTimeout(timer);};
 },[projectId,connected,onActive]);
 const s=status?.projectId===projectId?status:undefined;const p=s?.profile;const currentLog=log&&log.projectId===projectId&&(log.buildId===s?.activeBuildId||log.buildId===s?.latestResult?.buildId)?log:undefined;
 async function start(){if(!projectId||!p||pending)return;setPending(true);setError('');const gen=generation.current;try{await buildRequest('/api/build',{projectId,profileId:p.id});if(gen!==generation.current)return;setClear({buildId:'',sequence:0});onActive(true);setStatus(validateBuildSnapshot(await buildRequest('/api/build/status'),projectId));}catch(e){if(gen===generation.current)setError(e instanceof Error?e.message:'Build failed');}finally{setPending(false);}}
 const m=s?.lastSuccessfulBuild;
 return <section className="build-panel" aria-label="Controlled Build"><h3>Build</h3><p>Managed source root: {p?.managedSourceRoot??snapshot?.session.projectRoot}</p>{p&&<details><summary>Build Profile · {p.displayName}</summary><dl><dt>Profile ID</dt><dd>{p.id}</dd><dt>Build directory</dt><dd>{p.managedSourceRoot}/{p.buildDirRelative}</dd><dt>Target</dt><dd>{p.target}</dd><dt>Expected executable</dt><dd>{p.managedSourceRoot}/{p.outputBinaryRelative}</dd><dt>Registered case ID (configured)</dt><dd>{p.caseId??'unknown'} · unified ARCH executable</dd><dt>Parallel jobs</dt><dd>{p.parallelism}</dd><dt>Tracked inputs (incomplete dependency coverage)</dt><dd>{p.trackedInputs.join(', ')}</dd></dl></details>}
 <p aria-label="Build state">Build: {s?.state??'not-configured'}</p>{s?.reason&&<p>{s.reason}</p>}<button disabled={!connected||!snapshot?.host.capabilities.build||!s?.configured||!!s.activeBuildId||pending} onClick={()=>void start()}>{pending||s?.activeBuildId?'Building…':'Build'}</button>
 {error&&<p role="alert">{error}</p>}{s?.latestResult?.error&&<p role="alert">{s.latestResult.error}</p>}
 <p>Mapping: {s?.mappingState??'unknown'} · not independently verified by Core</p><p aria-label="Binary build state">Binary: {s?.binaryState??'freshness-unknown'}</p><p>{s?.freshnessReason}</p>{!!s?.changedInputs.length&&<p>Changed tracked inputs: {s.changedInputs.join(', ')}</p>}
 {m&&<details><summary>Last successful Build · {m.finishedAt}</summary><dl><dt>Build ID</dt><dd>{m.buildId}</dd><dt>Managed source root</dt><dd>{m.managedSourceRoot}</dd><dt>Source Git HEAD</dt><dd>{m.sourceGitHead??'unknown'}</dd><dt>Repository dirty at build</dt><dd>{m.repositoryDirty===undefined?'unknown':String(m.repositoryDirty)} (separate from tracked-input freshness)</dd><dt>Binary SHA-256</dt><dd>{m.outputBinary.fingerprint.sha256}</dd><dt>Profile fingerprint</dt><dd>{m.buildProfileFingerprint}</dd></dl></details>}
 <details><summary>Build Output</summary>{currentLog?.truncated&&<p>Earlier build output truncated in Studio view.</p>}<button onClick={()=>setClear({buildId:currentLog?.buildId??'',sequence:currentLog?.lastSequence??0})}>Clear view</button><pre className="build-log" tabIndex={0}>{currentLog?.events.filter(e=>(currentLog.buildId!==clear.buildId||e.sequence>clear.sequence)).map(e=>`[${e.sequence} ${e.kind}] ${e.text??e.state??''}`).join('\n')??'No build output.'}</pre></details><p>Build does not save config, run simulation or generate Preview.</p></section>;
}
