import type {AmrMesh} from '../../host/workflowContracts';
import {amrAxisLabel,amrAxisUnit,amrLevelColor} from '../../data/amrGeometry';
export function AmrControls({mesh,levels,cells,selecting,selected,onLevels,onCells,onSelecting,onSelect}:{mesh:AmrMesh;levels:ReadonlySet<number>;cells:boolean;selecting:boolean;selected:string|null;onLevels:(v:Set<number>)=>void;onCells:(v:boolean)=>void;onSelecting:(v:boolean)=>void;onSelect:(v:string)=>void}){
 const leaf=mesh.leaves.find(l=>l.logicalKey===selected&&levels.has(l.level));
 return <section aria-label="AMR display and block Inspector"><h4>AMR display · {mesh.complete?'Complete':'Limited / Incomplete'}</h4><p>Block outlines show the real initial hierarchy. Fine lines show active cells when resolved by zoom. Field colors remain separate Init samples, not AMR cell averages.</p><div className="real-preview-actions"><label><input type="checkbox" checked={cells} onChange={e=>onCells(e.target.checked)}/>Cell lines</label><label><input type="checkbox" checked={selecting} onChange={e=>onSelecting(e.target.checked)}/>Select AMR block on plot</label>{mesh.levelCounts.map(l=><label key={l.level} style={{color:amrLevelColor(l.level)}}><input type="checkbox" checked={levels.has(l.level)} onChange={e=>{const next=new Set(levels);if(e.target.checked)next.add(l.level);else next.delete(l.level);onLevels(next);}}/>Level {l.level} ({l.leafBlocks})</label>)}</div>
 <label>Block <select aria-label="AMR block" value={leaf?.logicalKey??''} onChange={e=>onSelect(e.target.value)}><option value="">Select a logical block</option>{mesh.leaves.filter(l=>levels.has(l.level)).map(l=><option key={l.logicalKey} value={l.logicalKey}>{l.logicalKey}</option>)}</select></label>
 {leaf?<dl aria-label="AMR block Inspector"><dt>logicalKey</dt><dd>{leaf.logicalKey}</dd><dt>level</dt><dd>{leaf.level}</dd><dt>logicalIndex</dt><dd>{leaf.logicalIndex.join(', ')}</dd><dt>lower</dt><dd>{leaf.lower.map((v,a)=>amrAxisLabel(mesh,a)+': '+v+' '+(amrAxisUnit(mesh,a)??'Unit not provided')).join('; ')}</dd><dt>upper</dt><dd>{leaf.upper.map((v,a)=>amrAxisLabel(mesh,a)+': '+v+' '+(amrAxisUnit(mesh,a)??'Unit not provided')).join('; ')}</dd><dt>cellShape</dt><dd>{leaf.cellShape.join(' × ')}</dd><dt>cellSpacing</dt><dd>{leaf.cellSpacing.map((v,a)=>amrAxisLabel(mesh,a)+': '+v+' '+(amrAxisUnit(mesh,a)??'Unit not provided')).join('; ')}</dd><dt>AMR cell field arrays</dt><dd>Not provided by this API.</dd></dl>:<p>Select a block to inspect its geometry. No AMR cell values are inferred.</p>}
 </section>;
}
