#!/usr/bin/env python3
"""Safely generate and register an ARCH custom pynucastro SimpleCxx network."""
from __future__ import annotations
import argparse, hashlib, importlib.util, json, os, re, shutil, tempfile
from datetime import datetime, timezone
from pathlib import Path

GENERATOR_VERSION = 1
ID_RE = re.compile(r"^[a-z][a-z0-9_]{0,47}$")
RESERVED = {"custom", "none", "null", "ideal", "helmholtz", "tabular"}

def fail(message): raise SystemExit(f"GenerateNetwork: {message}")

def load_recipe(path):
    spec = importlib.util.spec_from_file_location("arch_custom_network_recipe", path)
    if spec is None or spec.loader is None: fail(f"cannot load recipe: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module

def validate_id(value):
    if not isinstance(value, str) or not ID_RE.fullmatch(value):
        fail("NETWORK_ID must match ^[a-z][a-z0-9_]{0,47}$")
    if value in RESERVED or value.startswith(("aprox", "iso")):
        fail(f"NETWORK_ID '{value}' is reserved; custom generation can never replace aprox*/iso* networks")
    return value

def default_network(recipe, pyna):
    if not hasattr(recipe, "NUCLEI"):
        fail("recipe must define build_network(pynucastro) or NUCLEI")
    nuclei = [pyna.Nucleus.from_cache(name) for name in recipe.NUCLEI]
    library = pyna.ReacLibLibrary().linking_nuclei(
        nuclei, with_reverse=bool(getattr(recipe, "WITH_REVERSE", True)),
        print_warning=bool(getattr(recipe, "PRINT_RATE_WARNINGS", True)))
    return pyna.SimpleCxxNetwork(
        libraries=library, do_screening=bool(getattr(recipe, "DO_SCREENING", True)))

def rewrite_local_includes(generated_dir):
    names = {p.name for p in generated_dir.glob("*.H")}
    pattern = re.compile(r"^(\s*#include\s*)<([^>]+)>(\s*)$", re.MULTILINE)
    for path in generated_dir.glob("*.H"):
        text = path.read_text(encoding="utf-8")
        text = pattern.sub(lambda m: f'{m.group(1)}"{m.group(2)}"{m.group(3)}'
                           if m.group(2) in names else m.group(0), text)
        path.write_text(text, encoding="utf-8")

def cpp_array(values): return ", ".join(f"{float(v):.17g}" for v in values)
def quoted_array(values): return ", ".join(json.dumps(str(v)) for v in values)

def validated_nuclei(network):
    nuclei = list(network.unique_nuclei)
    if not nuclei: fail("pynucastro produced a network with zero nuclei")
    incomplete = [n.short_spec_name for n in nuclei
                  if n.mass is None or n.A_nuc is None]
    if incomplete:
        fail("pynucastro has incomplete mass data for: " +
             ", ".join(incomplete))
    return nuclei

def write_adapter(stage, network_id, network):
    cls = f"NetCustom_{network_id}"
    detail = f"arch_custom_{network_id}_detail"
    generated = f"arch_pynucastro_{network_id}"
    nuclei = validated_nuclei(network)
    names = [n.short_spec_name.lower() for n in nuclei]
    aion, zion = [n.A for n in nuclei], [n.Z for n in nuclei]
    c_light = 2.99792458e10
    mev_to_gram = 1.0e6 * 1.602176487e-12 / c_light**2
    masses = [n.mass * mev_to_gram for n in nuclei]
    conversion = -6.02214129e23 * c_light**2
    header_name, source_name = f"{cls}.h", f"{cls}.cpp"

    header = f'''/** Generated by tools/network/GenerateNetwork.py. Do not edit. */
#pragma once
#include <algorithm>
#include <array>
#include <cctype>
#include <stdexcept>
#include <string>
#include <vector>
#include "core/RuntimeParams.h"
#include "physics/species/Species.h"

namespace {detail} {{
void eval_rhs(const double*, double, double*, double&);
void eval_jacobian_entries(const double*, double, std::vector<int>&,
                           std::vector<int>&, std::vector<double>&, double*);
void eval_temperature_derivative(const double*, double, double*, double&);
}}

struct {cls} {{
    static constexpr int NUM_SPECIES = {len(nuclei)};
    static constexpr int ODE_NEQ = NUM_SPECIES + 1;
    static constexpr bool SUPPORTS_NSE = false;
    static constexpr const char* NETWORK_NAME = "custom:{network_id}";
    inline static constexpr std::array<const char*, NUM_SPECIES> SPECIES_NAMES{{{quoted_array(names)}}};
    inline static constexpr std::array<double, NUM_SPECIES> AION{{{cpp_array(aion)}}};
    inline static constexpr std::array<double, NUM_SPECIES> ZION{{{cpp_array(zion)}}};
    inline static constexpr std::array<double, NUM_SPECIES> ENERGY_WEIGHTS{{{cpp_array(masses)}}};
    static constexpr double ENERGY_CONVERSION = {conversion:.17g};

    static std::string get_network_name() {{ return NETWORK_NAME; }}
    static void RegisterSpecies(SpeciesManager& specs) {{
        for (int i = 0; i < NUM_SPECIES; ++i)
            specs.add_species(SPECIES_NAMES[i], AION[i], ZION[i], 5.0/3.0, 0.0);
    }}
    static void SetupInitialFractions(SimConfig& config, const SpeciesManager& specs,
                                      std::vector<double>& output) {{
        output.assign(specs.count(), config.physics.burn.smallx);
        double sum = 0.0;
        for (int i = 0; i < specs.count(); ++i) {{
            std::string target = "x" + specs.get_name(i);
            std::transform(target.begin(), target.end(), target.begin(),
                [](unsigned char c) {{ return static_cast<char>(std::tolower(c)); }});
            for (const auto& entry : config.custom_params) {{
                std::string key = entry.first;
                std::transform(key.begin(), key.end(), key.begin(),
                    [](unsigned char c) {{ return static_cast<char>(std::tolower(c)); }});
                if (key == target) {{ output[i] += entry.second; break; }}
            }}
            sum += output[i];
        }}
        if (!(sum > 0.0)) throw std::runtime_error("custom network initial composition has zero sum");
        for (double& value : output) value /= sum;
    }}
    static void eval_rhs(const double* state, double rho, double, double* rhs, double& enuc) {{
        {detail}::eval_rhs(state, rho, rhs, enuc);
    }}
    template <typename MatrixType>
    static void eval_jacobian(const double* state, double rho, double, MatrixType& jac,
                              double* denuc_dX = nullptr) {{
        std::vector<int> rows, columns;
        std::vector<double> values;
        {detail}::eval_jacobian_entries(state, rho, rows, columns, values, denuc_dX);
        for (std::size_t k = 0; k < values.size(); ++k)
            jac.set(rows[k], columns[k], values[k]);
    }}
    static void eval_temperature_derivative(const double* state, double rho, double,
                                             double* drhs_dT, double& denuc_dT) {{
        {detail}::eval_temperature_derivative(state, rho, drhs_dT, denuc_dT);
    }}
}};
'''
    (stage/header_name).write_text(header, encoding="utf-8")
    screen_on = "#define SCREENING 1\n" if network.do_screening else ""
    screen_off = "#undef SCREENING\n" if network.do_screening else ""
    source = f'''#include "{header_name}"
#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <numbers>
#include <sstream>
#include <string>
#include <type_traits>
#include <vector>

namespace {generated} {{
{screen_on}#include "generated/actual_rhs.H"
{screen_off}}}

namespace {detail} {{
using Network = {cls};
static {generated}::burn_t make_state(const double* state, double rho) {{
    {generated}::burn_t burn{{}};
    burn.rho = rho; burn.T = state[Network::NUM_SPECIES];
    for (int i=0; i<Network::NUM_SPECIES; ++i) burn.xn[i] = state[i];
    return burn;
}}
void eval_rhs(const double* state, double rho, double* rhs, double& enuc) {{
    auto burn = make_state(state, rho);
    {generated}::Array1D<double, 1, {generated}::NumSpec> dydt{{}};
    double enu_weak = 0.0;
    {generated}::actual_rhs(burn, dydt, enu_weak);
    for (int i=0; i<Network::NUM_SPECIES; ++i) rhs[i] = dydt(i+1)*Network::AION[i];
    {generated}::ener_gener_rate(dydt, enuc);
    enuc += enu_weak;
}}
struct JacobianSink {{
    std::vector<int>& rows; std::vector<int>& columns; std::vector<double>& values;
    void zero() {{ rows.clear(); columns.clear(); values.clear(); }}
    void set(int row, int column, double value) {{
        rows.push_back(row); columns.push_back(column);
        values.push_back(value*Network::AION[row-1]/Network::AION[column-1]);
    }}
}};
void eval_jacobian_entries(const double* state, double rho, std::vector<int>& rows,
                           std::vector<int>& columns, std::vector<double>& values,
                           double* denuc_dX) {{
    auto burn = make_state(state, rho);
    JacobianSink sink{{rows, columns, values}};
    {generated}::actual_jac(burn, sink);
    if (denuc_dX) {{
        std::fill(denuc_dX, denuc_dX+Network::NUM_SPECIES, 0.0);
        for (std::size_t k=0; k<values.size(); ++k) {{
            int row=rows[k]-1, column=columns[k]-1;
            denuc_dX[column] += Network::ENERGY_CONVERSION * values[k] /
                Network::AION[row] * Network::ENERGY_WEIGHTS[row];
        }}
    }}
}}
void eval_temperature_derivative(const double* state, double rho,
                                 double* drhs_dT, double& denuc_dT) {{
    const double temperature=state[Network::NUM_SPECIES];
    const double delta=std::max(std::abs(temperature)*1.0e-4, 1.0);
    std::vector<double> upper(state, state+Network::ODE_NEQ), lower=upper;
    upper[Network::NUM_SPECIES]=temperature+delta;
    lower[Network::NUM_SPECIES]=std::max(temperature-delta, 1.0);
    std::vector<double> fr(Network::NUM_SPECIES), fl(Network::NUM_SPECIES);
    double er=0.0, el=0.0;
    eval_rhs(upper.data(), rho, fr.data(), er);
    eval_rhs(lower.data(), rho, fl.data(), el);
    const double inv=1.0/(upper[Network::NUM_SPECIES]-lower[Network::NUM_SPECIES]);
    for (int i=0; i<Network::NUM_SPECIES; ++i) drhs_dT[i]=(fr[i]-fl[i])*inv;
    denuc_dT=(er-el)*inv;
}}
}}
'''
    (stage/source_name).write_text(source, encoding="utf-8")
    return cls, header_name, source_name

def main():
    parser=argparse.ArgumentParser(description="Generate an isolated ARCH custom network.")
    parser.add_argument("recipe", type=Path)
    parser.add_argument("--replace", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--custom-root", type=Path, default=None, help=argparse.SUPPRESS)
    args=parser.parse_args()
    recipe_path=args.recipe.resolve()
    if not recipe_path.is_file(): fail(f"recipe does not exist: {recipe_path}")
    recipe=load_recipe(recipe_path)
    network_id=validate_id(getattr(recipe, "NETWORK_ID", None))
    repo_root=Path(__file__).resolve().parents[2]
    custom_root=(args.custom_root.resolve() if args.custom_root else
                 repo_root/"src"/"physics"/"network"/"custom")
    custom_root.mkdir(parents=True, exist_ok=True)
    target=custom_root/network_id
    if target.parent.resolve()!=custom_root.resolve(): fail("target escaped custom root")
    try: import pynucastro as pyna
    except ImportError: fail("run with: conda run -n p311 python tools/network/GenerateNetwork.py ...")
    recipe_hash=hashlib.sha256(recipe_path.read_bytes()).hexdigest()
    if target.exists() and not args.replace:
        manifest_path=target/"manifest.json"
        if manifest_path.is_file():
            m=json.loads(manifest_path.read_text())
            if (m.get("recipe_sha256")==recipe_hash and m.get("pynucastro_version")==pyna.__version__
                    and m.get("generator_version")==GENERATOR_VERSION):
                print(f"custom:{network_id} is already up to date; no files changed"); return
        fail(f"custom:{network_id} exists; choose another ID or pass --replace")
    network=(recipe.build_network(pyna) if hasattr(recipe, "build_network")
             else default_network(recipe, pyna))
    if not isinstance(network, pyna.SimpleCxxNetwork):
        fail("build_network() must return pynucastro.SimpleCxxNetwork")
    validated_nuclei(network)
    if args.check:
        print(f"validated custom:{network_id}: {len(network.unique_nuclei)} nuclei, "
              f"{len(network.rates)} rates, pynucastro {pyna.__version__}"); return
    stage=Path(tempfile.mkdtemp(prefix=f".{network_id}.", dir=custom_root))
    try:
        generated_dir=stage/"generated"; generated_dir.mkdir()
        network.write_network(odir=generated_dir); rewrite_local_includes(generated_dir)
        cls, header, source=write_adapter(stage, network_id, network)
        manifest={"schema_version":1, "generator_version":GENERATOR_VERSION,
            "network_id":network_id, "runtime_name":f"custom:{network_id}",
            "class_name":cls, "header":header, "source":source,
            "pynucastro_version":pyna.__version__, "recipe":str(recipe_path),
            "recipe_sha256":recipe_hash, "species_count":len(network.unique_nuclei),
            "species":[n.short_spec_name.lower() for n in network.unique_nuclei],
            "rate_count":len(network.rates), "supports_nse":False,
            "temperature_jacobian":"centered finite difference, relative step 1e-4"}
        (stage/"manifest.json").write_text(json.dumps(manifest,indent=2,sort_keys=True)+"\n")
        (stage/"network.cmake").write_text(
            f'set(ARCH_CUSTOM_NETWORK_ID "{network_id}")\n'
            f'set(ARCH_CUSTOM_NETWORK_TYPE "{cls}")\n'
            f'set(ARCH_CUSTOM_NETWORK_HEADER "${{CMAKE_CURRENT_LIST_DIR}}/{header}")\n'
            f'set(ARCH_CUSTOM_NETWORK_SOURCE "${{CMAKE_CURRENT_LIST_DIR}}/{source}")\n')
        if target.exists():
            backup_root=custom_root/".backup"; backup_root.mkdir(exist_ok=True)
            backup=backup_root/f"{network_id}-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"
            os.replace(target, backup); print(f"preserved previous network at {backup}")
        os.replace(stage, target)
    except Exception:
        if stage.exists(): shutil.rmtree(stage)
        raise
    print(f"generated custom:{network_id}: {len(network.unique_nuclei)} nuclei, "
          f"{len(network.rates)} rates; rerun CMake to register it")

if __name__=="__main__": main()
