import {plotColor} from '../../data/plotColors';
import type {AxisSetting,FieldSetting} from '../../data/plotPresentation';
import {axisDefault,fieldDefault} from '../../data/plotPresentation';
function AxisControls({name,value,onChange}:{name:string;value:AxisSetting;onChange:(s:AxisSetting)=>void}){
 return <div className="plot-setting-row"><label>{name} scale <select aria-label={`${name} scale`} value={value.scale} onChange={e=>onChange({...value,scale:e.target.value as AxisSetting['scale']})}><option value="linear">Linear</option><option value="log">Log</option></select></label><label>{name} range <select aria-label={`${name} range`} value={value.manual?'manual':'auto'} onChange={e=>onChange({...value,manual:e.target.value==='manual'})}><option value="auto">Auto</option><option value="manual">Manual</option></select></label>{value.manual&&<><label>Min <input aria-label={`${name} minimum`} value={value.min} onChange={e=>onChange({...value,min:e.target.value})}/></label><label>Max <input aria-label={`${name} maximum`} value={value.max} onChange={e=>onChange({...value,max:e.target.value})}/></label></>}</div>;
}
export function PlotControls({twoD,x,y,field,onX,onY,onField}:{twoD:boolean;x:AxisSetting;y:AxisSetting;field:FieldSetting;onX:(v:AxisSetting)=>void;onY:(v:AxisSetting)=>void;onField:(v:FieldSetting)=>void}){
 const gradient=`linear-gradient(to right,${Array.from({length:17},(_,i)=>plotColor(field.map,i/16)).join(',')})`;
 return <details className="plot-controls"><summary>Plot presentation · display only</summary><div className="plot-setting-groups"><fieldset><legend>Coordinate Axes</legend><AxisControls name="X" value={x} onChange={onX}/>{twoD&&<AxisControls name="Y" value={y} onChange={onY}/>}<button onClick={()=>{onX(axisDefault());onY(axisDefault());}}>Reset Coordinate Axes</button></fieldset><fieldset><legend>Field Values</legend><AxisControls name="Field" value={field} onChange={v=>onField({...field,...v})}/>{(['lower','upper'] as const).map(side=><div className="plot-setting-row" key={side}><label><input type="checkbox" checked={field[side]} onChange={e=>onField({...field,[side]:e.target.checked})}/>{side==='lower'?'Lower':'Upper'} clipping</label>{field[side]&&<label>Threshold <input aria-label={`${side} clipping threshold`} value={side==='lower'?field.low:field.high} onChange={e=>onField({...field,[side==='lower'?'low':'high']:e.target.value})}/></label>}</div>)}<label>Colormap <select aria-label="Field colormap" value={field.map} onChange={e=>onField({...field,map:e.target.value as FieldSetting['map']})}><option>Viridis</option><option>Hot</option></select></label><span className="colormap-preview" role="img" aria-label={`${field.map} gradient`} style={{background:gradient}}/><button onClick={()=>onField(fieldDefault())}>Reset Field Values</button></fieldset></div><p className="section-note">Original physical values. Display only: no Save, Config edit or Core Preview. Inspector always shows raw samples.</p></details>;
}
