import type {ConfigurationCase,ConfigurationBuildScope,SchemaResponse,InspectionResponse} from '../host/configurationContracts';
import {createContext,useContext,useState} from 'react';
import type {ReactNode} from 'react';
import type {RealPreviewResult} from '../host/previewContracts';
import {useRef,useCallback} from 'react';
interface Snapshot {result:RealPreviewResult;text:string}
interface Context {model:ConfigurationCase;setModel:(v:ConfigurationCase)=>void;buildScope:ConfigurationBuildScope|null;setBuildScope:(v:ConfigurationBuildScope|null)=>void;schema:SchemaResponse|null;setSchema:(v:SchemaResponse|null)=>void;inspection:{text:string;response:InspectionResponse}|null;setInspection:(v:{text:string;response:InspectionResponse}|null)=>void;inspectionMessage:string;setInspectionMessage:(v:string)=>void;snapshot:Snapshot|null;setSnapshot:(v:Snapshot|null)=>void;candidate:number|null;setCandidate:(v:number|null)=>void;edit:(key:string,value:string)=>void;focus:(key:string)=>void;registerFocus:(fn:((key:string)=>void)|null)=>void;registerEdit:(fn:((key:string,value:string)=>void)|null)=>void}
const CoreContext=createContext<Context|null>(null);
export function CoreParameterProvider({children}:{children:ReactNode}){const [model,setModel]=useState<ConfigurationCase>('Sod');const [buildScope,setBuildScope]=useState<ConfigurationBuildScope|null>(null);const [schema,setSchema]=useState<SchemaResponse|null>(null);const [inspection,setInspection]=useState<{text:string;response:InspectionResponse}|null>(null);const [inspectionMessage,setInspectionMessage]=useState('Configuration inspection unavailable');const [snapshot,setSnapshot]=useState<Snapshot|null>(null);const [candidate,setCandidate]=useState<number|null>(null);const edit=useRef<((key:string,value:string)=>void)|null>(null);const focus=useRef<((key:string)=>void)|null>(null);const registerFocus=useCallback((fn:((key:string)=>void)|null)=>{focus.current=fn;},[]);const focusKey=useCallback((key:string)=>focus.current?.(key),[]);const registerEdit=useCallback((fn:((key:string,value:string)=>void)|null)=>{edit.current=fn;},[]);const applyEdit=useCallback((key:string,value:string)=>edit.current?.(key,value),[]);return <CoreContext.Provider value={{model,setModel,buildScope,setBuildScope,schema,setSchema,inspection,setInspection,inspectionMessage,setInspectionMessage,snapshot,setSnapshot,candidate,setCandidate,edit:applyEdit,registerEdit,focus:focusKey,registerFocus}}>{children}</CoreContext.Provider>;}
// Hook and provider share this small state boundary.
// eslint-disable-next-line react-refresh/only-export-components
export function useCoreParameters(){const c=useContext(CoreContext);if(!c)throw new Error('Core parameter context missing');return c;}
