import {fingerprint,checkedPath} from './files.ts';
import {profileFingerprint} from './buildProfile.ts';
import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {mkdir,open,rename,unlink} from 'node:fs/promises';import {constants} from 'node:fs';import {randomUUID,createHash} from 'node:crypto';
import type {BuildProfile,FileFingerprint,InputFingerprint,BuildManifest} from '../src/host/contracts.ts';
export async function inspect(root:string,relative:string,binary=false):Promise<FileFingerprint>{const f=await fingerprint(root,relative,binary?'executable':'case-source');if(!f.exists||f.error||!f.sha256||f.size===undefined||!f.modifiedTime)throw new Error(binary?'Expected executable is missing or cannot be fingerprinted.':`Tracked input unavailable: ${relative}`);return {sha256:f.sha256,size:f.size,modifiedTime:f.modifiedTime};}
export async function inputs(p:BuildProfile):Promise<InputFingerprint[]>{const paths=[...new Set([...(p.sourceRelativePath?[p.sourceRelativePath]:[]),...p.trackedInputs])];const list:InputFingerprint[]=[];for(const relativePath of paths)list.push({relativePath,fingerprint:await inspect(p.managedSourceRoot,relativePath)});return list;}
export function same(a:FileFingerprint,b:FileFingerprint){return a.sha256===b.sha256&&a.size===b.size&&a.modifiedTime===b.modifiedTime;}
export function sameInputs(a:InputFingerprint[],b:InputFingerprint[]){return a.length===b.length&&a.every(x=>b.some(y=>y.relativePath===x.relativePath&&same(x.fingerprint,y.fingerprint)));}
export async function gitIdentity(root:string){try{const env={PATH:'/usr/bin:/bin',HOME:process.env.HOME??'/home/arch',GIT_OPTIONAL_LOCKS:'0'};const exec=promisify(execFile);const head=await exec('/usr/bin/git',['-C',root,'rev-parse','HEAD'],{env,timeout:3000,maxBuffer:262144});const status=await exec('/usr/bin/git',['-C',root,'status','--porcelain'],{env,timeout:3000,maxBuffer:262144});return {sourceGitHead:head.stdout.trim(),repositoryDirty:!!status.stdout.trim()};}catch{return {};}}
function filename(p:BuildProfile){return 'build-'+createHash('sha256').update(p.id).digest('hex').slice(0,24)+'.json';}
async function stateDirectory(root:string,create:boolean){await checkedPath(root,'studio');if(create){await mkdir(root+'/studio/.local',{recursive:false}).catch((e:NodeJS.ErrnoException)=>{if(e.code!=='EEXIST')throw e;});}return checkedPath(root,'studio/.local');}
export async function saveManifest(p:BuildProfile,m:BuildManifest){const directory=await stateDirectory(p.managedSourceRoot,true);const dir=await open(directory,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW);const temp=`/proc/self/fd/${dir.fd}/.build-${randomUUID()}.tmp`;const target=`/proc/self/fd/${dir.fd}/${filename(p)}`;let created=false;try{const f=await open(temp,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY|constants.O_NOFOLLOW,0o600);created=true;try{await f.writeFile(JSON.stringify(m,null,2));await f.sync();}finally{await f.close();}await checkedPath(p.managedSourceRoot,'studio/.local');await rename(temp,target);created=false;await dir.sync().catch(()=>undefined);}finally{if(created)await unlink(temp).catch(()=>undefined);await dir.close();}}
export async function loadManifest(p:BuildProfile):Promise<BuildManifest|undefined>{try{await stateDirectory(p.managedSourceRoot,false);const target=await checkedPath(p.managedSourceRoot,'studio/.local/'+filename(p));const f=await open(target,constants.O_RDONLY|constants.O_NOFOLLOW|constants.O_NONBLOCK);let m:BuildManifest;try{const s=await f.stat();if(!s.isFile()||s.size>256*1024)return;m=JSON.parse(await f.readFile('utf8'));}finally{await f.close();}if(m.manifestVersion!=='1'||m.managedSourceRoot!==p.managedSourceRoot||m.profileId!==p.id||typeof m.buildId!=='string'||typeof m.buildProfileFingerprint!=='string'||!Array.isArray(m.trackedInputFingerprints)||!Array.isArray(m.preBuildInputFingerprints)||m.trackedInputFingerprints.length>128||typeof m.inputsStableDuringBuild!=='boolean'||!m.outputBinary?.fingerprint?.sha256)return;for(const x of m.trackedInputFingerprints){if(typeof x.relativePath!=='string'||typeof x.fingerprint?.sha256!=='string')return;}return m;}catch{return;}}
export async function makeManifest(p:BuildProfile,projectId:string,buildId:string,startedAt:string,before:InputFingerprint[],preBinary:FileFingerprint|undefined,git:Awaited<ReturnType<typeof gitIdentity>>):Promise<BuildManifest>{const after=await inputs(p);const binary=await inspect(p.managedSourceRoot,p.outputBinaryRelative,true);return {manifestVersion:'1',projectId,profileId:p.id,caseId:p.caseId,managedSourceRoot:p.managedSourceRoot,buildId,startedAt,finishedAt:new Date().toISOString(),...git,buildProfileFingerprint:profileFingerprint(p),sourceFingerprint:after.find(x=>x.relativePath===p.sourceRelativePath)?.fingerprint,trackedInputFingerprints:after,preBuildInputFingerprints:before,inputsStableDuringBuild:sameInputs(before,after),buildDirectory:p.managedSourceRoot+'/'+p.buildDirRelative,target:p.target,outputBinary:{relativePath:p.outputBinaryRelative,absolutePath:p.managedSourceRoot+'/'+p.outputBinaryRelative,fingerprint:binary},preBuildBinaryFingerprint:preBinary};}
